default_install_hook_types: [prepare-commit-msg]
repos:
  - repo: local
    hooks:
      - id: prepare-msg
        name: prepare commit message
        entry: koji --hook 
        language: system
        stages: [prepare-commit-msg]
